# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Tristan/Documents/Nexys-Video-HDMI-master/proj/Nexys-Video-HDMI-master.srcs/sources_1/bd/hdmi/ip/hdmi_rst_axi_dynclk_0_100M_0/hdmi_rst_axi_dynclk_0_100M_0.xci
# IP: The module: 'hdmi_rst_axi_dynclk_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Tristan/Documents/Nexys-Video-HDMI-master/proj/Nexys-Video-HDMI-master.srcs/sources_1/bd/hdmi/ip/hdmi_rst_axi_dynclk_0_100M_0/hdmi_rst_axi_dynclk_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_rst_axi_dynclk_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Tristan/Documents/Nexys-Video-HDMI-master/proj/Nexys-Video-HDMI-master.srcs/sources_1/bd/hdmi/ip/hdmi_rst_axi_dynclk_0_100M_0/hdmi_rst_axi_dynclk_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_rst_axi_dynclk_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Tristan/Documents/Nexys-Video-HDMI-master/proj/Nexys-Video-HDMI-master.srcs/sources_1/bd/hdmi/ip/hdmi_rst_axi_dynclk_0_100M_0/hdmi_rst_axi_dynclk_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_rst_axi_dynclk_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Tristan/Documents/Nexys-Video-HDMI-master/proj/Nexys-Video-HDMI-master.srcs/sources_1/bd/hdmi/ip/hdmi_rst_axi_dynclk_0_100M_0/hdmi_rst_axi_dynclk_0_100M_0.xci
# IP: The module: 'hdmi_rst_axi_dynclk_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Tristan/Documents/Nexys-Video-HDMI-master/proj/Nexys-Video-HDMI-master.srcs/sources_1/bd/hdmi/ip/hdmi_rst_axi_dynclk_0_100M_0/hdmi_rst_axi_dynclk_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_rst_axi_dynclk_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Tristan/Documents/Nexys-Video-HDMI-master/proj/Nexys-Video-HDMI-master.srcs/sources_1/bd/hdmi/ip/hdmi_rst_axi_dynclk_0_100M_0/hdmi_rst_axi_dynclk_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_rst_axi_dynclk_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Tristan/Documents/Nexys-Video-HDMI-master/proj/Nexys-Video-HDMI-master.srcs/sources_1/bd/hdmi/ip/hdmi_rst_axi_dynclk_0_100M_0/hdmi_rst_axi_dynclk_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_rst_axi_dynclk_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
