# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Tristan/Documents/Nexys-Video-HDMI-master/proj/Nexys-Video-HDMI-master.srcs/sources_1/bd/hdmi/ip/hdmi_axi_ethernet_0_0/hdmi_axi_ethernet_0_0.xci
# IP: The module: 'hdmi_axi_ethernet_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/Tristan/Documents/Nexys-Video-HDMI-master/proj/Nexys-Video-HDMI-master.srcs/sources_1/bd/hdmi/ip/hdmi_axi_ethernet_0_0/bd_0/bd_e87d.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e87d || ORIG_REF_NAME==bd_e87d} -quiet] -quiet

# IP: c:/Users/Tristan/Documents/Nexys-Video-HDMI-master/proj/Nexys-Video-HDMI-master.srcs/sources_1/bd/hdmi/ip/hdmi_axi_ethernet_0_0/bd_0/ip/ip_0/bd_e87d_eth_buf_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e87d_eth_buf_0 || ORIG_REF_NAME==bd_e87d_eth_buf_0} -quiet] -quiet

# IP: c:/Users/Tristan/Documents/Nexys-Video-HDMI-master/proj/Nexys-Video-HDMI-master.srcs/sources_1/bd/hdmi/ip/hdmi_axi_ethernet_0_0/bd_0/ip/ip_1/bd_e87d_mac_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e87d_mac_0 || ORIG_REF_NAME==bd_e87d_mac_0} -quiet] -quiet

# IP: c:/Users/Tristan/Documents/Nexys-Video-HDMI-master/proj/Nexys-Video-HDMI-master.srcs/sources_1/bd/hdmi/ip/hdmi_axi_ethernet_0_0/bd_0/ip/ip_2/bd_e87d_c_shift_ram_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e87d_c_shift_ram_0_0 || ORIG_REF_NAME==bd_e87d_c_shift_ram_0_0} -quiet] -quiet

# IP: c:/Users/Tristan/Documents/Nexys-Video-HDMI-master/proj/Nexys-Video-HDMI-master.srcs/sources_1/bd/hdmi/ip/hdmi_axi_ethernet_0_0/bd_0/ip/ip_3/bd_e87d_c_counter_binary_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e87d_c_counter_binary_0_0 || ORIG_REF_NAME==bd_e87d_c_counter_binary_0_0} -quiet] -quiet

# IP: c:/Users/Tristan/Documents/Nexys-Video-HDMI-master/proj/Nexys-Video-HDMI-master.srcs/sources_1/bd/hdmi/ip/hdmi_axi_ethernet_0_0/bd_0/ip/ip_4/bd_e87d_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e87d_xlconstant_0_0 || ORIG_REF_NAME==bd_e87d_xlconstant_0_0} -quiet] -quiet

# IP: c:/Users/Tristan/Documents/Nexys-Video-HDMI-master/proj/Nexys-Video-HDMI-master.srcs/sources_1/bd/hdmi/ip/hdmi_axi_ethernet_0_0/bd_0/ip/ip_5/bd_e87d_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e87d_util_vector_logic_0_0 || ORIG_REF_NAME==bd_e87d_util_vector_logic_0_0} -quiet] -quiet

# XDC: c:/Users/Tristan/Documents/Nexys-Video-HDMI-master/proj/Nexys-Video-HDMI-master.srcs/sources_1/bd/hdmi/ip/hdmi_axi_ethernet_0_0/bd_0/bd_e87d_ooc.xdc

# XDC: c:/Users/Tristan/Documents/Nexys-Video-HDMI-master/proj/Nexys-Video-HDMI-master.srcs/sources_1/bd/hdmi/ip/hdmi_axi_ethernet_0_0/hdmi_axi_ethernet_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_axi_ethernet_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Tristan/Documents/Nexys-Video-HDMI-master/proj/Nexys-Video-HDMI-master.srcs/sources_1/bd/hdmi/ip/hdmi_axi_ethernet_0_0/synth/hdmi_axi_ethernet_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_axi_ethernet_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/Tristan/Documents/Nexys-Video-HDMI-master/proj/Nexys-Video-HDMI-master.srcs/sources_1/bd/hdmi/ip/hdmi_axi_ethernet_0_0/hdmi_axi_ethernet_0_0.xci
# IP: The module: 'hdmi_axi_ethernet_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/Tristan/Documents/Nexys-Video-HDMI-master/proj/Nexys-Video-HDMI-master.srcs/sources_1/bd/hdmi/ip/hdmi_axi_ethernet_0_0/bd_0/bd_e87d.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e87d || ORIG_REF_NAME==bd_e87d} -quiet] -quiet

# IP: c:/Users/Tristan/Documents/Nexys-Video-HDMI-master/proj/Nexys-Video-HDMI-master.srcs/sources_1/bd/hdmi/ip/hdmi_axi_ethernet_0_0/bd_0/ip/ip_0/bd_e87d_eth_buf_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e87d_eth_buf_0 || ORIG_REF_NAME==bd_e87d_eth_buf_0} -quiet] -quiet

# IP: c:/Users/Tristan/Documents/Nexys-Video-HDMI-master/proj/Nexys-Video-HDMI-master.srcs/sources_1/bd/hdmi/ip/hdmi_axi_ethernet_0_0/bd_0/ip/ip_1/bd_e87d_mac_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e87d_mac_0 || ORIG_REF_NAME==bd_e87d_mac_0} -quiet] -quiet

# IP: c:/Users/Tristan/Documents/Nexys-Video-HDMI-master/proj/Nexys-Video-HDMI-master.srcs/sources_1/bd/hdmi/ip/hdmi_axi_ethernet_0_0/bd_0/ip/ip_2/bd_e87d_c_shift_ram_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e87d_c_shift_ram_0_0 || ORIG_REF_NAME==bd_e87d_c_shift_ram_0_0} -quiet] -quiet

# IP: c:/Users/Tristan/Documents/Nexys-Video-HDMI-master/proj/Nexys-Video-HDMI-master.srcs/sources_1/bd/hdmi/ip/hdmi_axi_ethernet_0_0/bd_0/ip/ip_3/bd_e87d_c_counter_binary_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e87d_c_counter_binary_0_0 || ORIG_REF_NAME==bd_e87d_c_counter_binary_0_0} -quiet] -quiet

# IP: c:/Users/Tristan/Documents/Nexys-Video-HDMI-master/proj/Nexys-Video-HDMI-master.srcs/sources_1/bd/hdmi/ip/hdmi_axi_ethernet_0_0/bd_0/ip/ip_4/bd_e87d_xlconstant_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e87d_xlconstant_0_0 || ORIG_REF_NAME==bd_e87d_xlconstant_0_0} -quiet] -quiet

# IP: c:/Users/Tristan/Documents/Nexys-Video-HDMI-master/proj/Nexys-Video-HDMI-master.srcs/sources_1/bd/hdmi/ip/hdmi_axi_ethernet_0_0/bd_0/ip/ip_5/bd_e87d_util_vector_logic_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e87d_util_vector_logic_0_0 || ORIG_REF_NAME==bd_e87d_util_vector_logic_0_0} -quiet] -quiet

# XDC: c:/Users/Tristan/Documents/Nexys-Video-HDMI-master/proj/Nexys-Video-HDMI-master.srcs/sources_1/bd/hdmi/ip/hdmi_axi_ethernet_0_0/bd_0/bd_e87d_ooc.xdc

# XDC: c:/Users/Tristan/Documents/Nexys-Video-HDMI-master/proj/Nexys-Video-HDMI-master.srcs/sources_1/bd/hdmi/ip/hdmi_axi_ethernet_0_0/hdmi_axi_ethernet_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_axi_ethernet_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Tristan/Documents/Nexys-Video-HDMI-master/proj/Nexys-Video-HDMI-master.srcs/sources_1/bd/hdmi/ip/hdmi_axi_ethernet_0_0/synth/hdmi_axi_ethernet_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_axi_ethernet_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
